//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "node")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  pub address: String,
  pub port: i16,
  pub secure: bool,
  #[sea_orm(column_type = "Double", nullable)]
  pub disk_limit_mb: Option<f64>,
  #[sea_orm(column_type = "Double", nullable)]
  pub memory_limit_mb: Option<f64>,
  pub cpu_limit: Option<i32>,
  pub token: String,
}

impl ActiveModelBehavior for ActiveModel {}
